### PR TITLE
I would like to offer an alternative solution to this issue. I must confe

### PR DESCRIPTION
**Pull request by emvaldes**
I would like to offer an alternative solution to this issue. I must confess that my understanding of git is limited but I have tried to resolved the same issue through this approach and it works great.

Please, take a look at it and see if you find this alternative implementation of any use. Any constructive comments are welcome.

Sincerely, Ed.

### CODE REVIEW

**Comment by dasch** [comment]
@emvaldes: thank you for the pull request! Can you explain exactly what this does, and why? It seems to add empty directories to the repository - I don't feel this should be done by an export mechanism. If you want to have empty directories available, just add `.gitkeep` files in them and add those to the index.

Are there other things this pull request changes?

**Comment by emvaldes** [comment]
Thank you very much for taking the time to look at my proposal.

My goal is to be able of exporting(archive) all directories regardless if they are empty or not. So far, I find this to be kind of an awkward limitation of Git.
Note: I am new to it and therefore are not sure why such 'restriction' although I am sure there is one but not clear yet to me.

I do not want to force any ghost file (e.g.: '.empty' or your suggestion of using '.gitkeep') into the Git-Repo but rather use a temporary process to deal with this and revert any changes back to the state before the 'Export'.
By doing this, we can avoid having blank files hanging around for nothing as much as to when personal settings files (e.g.: .settings/*, .buildpath, .project, etc.) are to be ignored and not pushed into the VCS-Repo.

Note: '.gitkeep' seems to be a better naming convention since '.empty' does not reflect the purpose of it. Thanks for that tip.

My Solution works without any problem (so far we haven't encountered any) and I am sorry for not developing it in Perl, Ruby or any of the new-tech trends.
There are now two processes that extend the 'archive' and 'checkout-index' functionalities to fit our needs.

I am fully aware that because of my lack of experience and perspective in Git, I might be re-inventing the wheel (not my intension and as soon as a formal solution is available I will jump to use it).

This my .gitrc file, I would like very much to share it with you. Please, if you can let me know what you think (constructive criticism is always welcome).
Please, feel free to remove the fork I made, I did it mostly while learning about the fork features in GitHub. Hope didn't cause any issues with your development.

Once again, thanks.

#!/bin/bash

GIT_ALIASES="${HOME}/.aliases/.git_aliases";
if [ -f "${GIT_ALIASES}" ]; then
    source "${GIT_ALIASES}"
  else echo -e "Missing: '${GIT_ALIASES}' file.";
fi

EMPTY_FILE=".empty";

function populate_empty () {

## Processing path (target-dir):

```
TRG_PATH="${1}";
```

## Component(s):

```
EXCLUDE_DIR=".git";
```

echo -en "\nAdding '${EMPTY_FILE}' files to empty folder(s): ...";
    find ${TRG_PATH} -not -path "_/${EXCLUDE_DIR}/_" -type d -empty -exec touch {}/${EMPTY_FILE} \;
#echo "done.";

## Purging SRC/TRG_DIRs variable(s):

```
unset TRG_PATH EMPTY_FILE EXCLUDE_DIR;
return 0;
```

  }

declare -a GIT_EXCLUDE;
function load_exclude () {
    SRC_PATH="${1}";
    ITEMS=0; while read LINE; do

# echo -e "Line [${ITEMS}]: '${LINE%%\ *}'";

```
  GIT_EXCLUDE[((ITEMS++))]=${LINE%%\ *};
done < ${SRC_PATH}/.gitattributes;
GIT_EXCLUDE[${ITEMS}]="${EMPTY_FILE}";
```

## Purging variable(s):

```
unset SRC_PATH ITEMS;
return 0;
```

  }

function purge_empty () {

## Processing path (Source/Target-dir):

```
SRC_PATH="${1}";
TRG_PATH="${2}";
```

echo -e "\nPurging Git-Specific component(s): ... ";
    find ${SRC_PATH} -type f -name ${EMPTY_FILE} -exec /bin/rm '{}' \;
    for xRULE in ${GIT_EXCLUDE[@]}; do
echo -en "    '${TRG_PATH}/{${xRULE}}' files ... ";
      find ${TRG_PATH} -type f -name "${xRULE}" -exec /bin/rm -rf '{}' \;
echo "done.'";
    done;
echo -e "done.\n"

## Purging SRC/TRG_PATHs variable(s):

```
unset SRC_PATH; unset TRG_PATH;
return 0;
```

  }

function git-export () {
    TRG_DIR="${1}"; SRC_DIR="${2}";
    if [ -z "${SRC_DIR}" ]; then SRC_DIR="${PWD}"; fi
    load_exclude "${SRC_DIR}";

## Dynamically added '.empty' files to the Git-Structure:

```
populate_empty "${SRC_DIR}";
GIT_COMMIT="Including '${EMPTY_FILE}' files into Git-Index container."; #echo -e "\n${GIT_COMMIT}";
git add .; git commit --quiet --all --verbose --message "${GIT_COMMIT}";
if [ "${?}" -eq 0 ]; then echo " done."; fi
/bin/rm -rf ${TRG_DIR} && mkdir -p "${TRG_DIR}";
```

echo -en "\nChecking-Out Index component(s): ... ";
    git checkout-index --prefix=${TRG_DIR}/ -q -f -a

## Reset: --mixed = reset HEAD and index:

```
if [ "${?}" -eq 0 ]; then
```

echo "done."; echo -en "Resetting HEAD and Index: ... ";
        git reset --soft HEAD^;
        if [ "${?}" -eq 0 ]; then
echo "done.";

## Purging Git-specific components and '.empty' files from Target-Dir:

```
        purge_empty "${SRC_DIR}" "${TRG_DIR}"
      else echo "failed.";
    fi
```

## Archiving exported-content:

echo -en "Archiving Checked-Out component(s): ... ";
        if [ -f "${TRG_DIR}.tgz" ]; then /bin/rm ${TRG_DIR}.tgz; fi
        cd ${TRG_DIR} && tar -czf ${TRG_DIR}.tgz ./; cd ${SRC_DIR}
echo "done.";

## Listing *.tgz file attributes:

## Warning: Un-TAR this file to a specific directory:

```
    ls -al ${TRG_DIR}.tgz
  else echo "failed.";
fi
```

## Purgin all references to Un-Staged File(s):

```
git reset HEAD;
echo "";
```

## Purging SRC/TRG_DIRs variable(s):

```
unset SRC_DIR TRG_DIR;
return 0;
```

  }

function git-archive () {
    PREFIX="${1}"; ## sudo mkdir -p ${PREFIX}
    REPO_PATH="`echo "${2}"|awk -F: '{print $1}'`";
    RELEASE="`echo "${2}"|awk -F: '{print $2}'`";
    USER_PATH="${PWD}";
echo "$PREFIX $REPO_PATH $RELEASE $USER_PATH";

## Dynamically added '.empty' files to the Git-Structure:

```
cd "${REPO_PATH}"; populate_empty .; echo -en "\n";
```

# git archive --prefix=git-1.4.0/ -o git-1.4.0.tar.gz v1.4.0

# e.g.: git-archive /var/www/htdocs /repos/flyerland.ca/flyerland:rel-1.0.0 --explode

```
OUTPUT_FILE="${USER_PATH}/${RELEASE}.tar.gz";
git archive --verbose --prefix=${PREFIX}/ -o ${OUTPUT_FILE} ${RELEASE}
cd "${USER_PATH}";
if [[ "${3}" =~ [--explode] ]]; then
  if [ -d "./${RELEASE}" ]; then /bin/rm -rf "./${RELEASE}"; fi
  mkdir -p ./${RELEASE}; tar -xzf "${OUTPUT_FILE}" -C ./${RELEASE}
fi
```

## Purging SRC/TRG_DIRs variable(s):

```
unset PREFIX REPO_PATH RELEASE USER_PATH OUTPUT_FILE;
return 0;
```

  }

**Comment by emvaldes** [comment]
In regards to other reasons as to why is important to manage the export/archive process through a process similar to the one I have suggested you to evaluate:

Since generic configurations (e.g.: developmenet environments, etc.) are in conflict with other sets (e.g.: qa, staging, uat and production, etc.), a process like this allows inject on-deman configurations (environment-based) to the repository while validating any conflicts but never made them part of the 'origin' data.

e.g.: Having a Git-Repo in a deployment server that pulls from 'origin' a specific tag/branch, updates global configurations with environment specific settings (e.g.: package to be build for production release) without having to make Git-Repo conscious of this switch of content.

Anyway, I am going too far ahead since at this point, I do not know yet what is your take on this idea.
Just let me know. I am very much interested in collaborating with anyone on these light-weight projects. ;)

Chao.

**Comment by dasch** [comment]
Hi @emvaldes - sorry for such a late reply, I've been swamped with other stuff.

I really appreciate the work you've done, but I just don't feel like this is a direction `git-export` should be going. The purpose of `export` is to export a tree from the _repository_, not the working tree. I feel that the need to always have some empty folders included is easily satisfied by the `.gitkeep` convention. If you need environment-specific configuration, I suggest using multiple config files/setups and a method for switching between them. This works great for Rails apps.

Thanks for taking the time to add this pull request, but I don't think the added complexity is worth it. You're of course free to fork the project and have your own version that suits your needs better.

Cheers,
Daniel Schierbeck

**Comment by emvaldes** [comment]
Thanks for your reply. I agree with your perspective of what the git-export should be.
I guess is a matter of just calling it something else. Take care and good luck to you too.

**Pull request closed without merging**
